plugin:
  # put the worlds you want to manage cooldowns and warmups in here
  worlds:
    - 'world'
    - 'world_nether'
  # enter the desired log prefix here (note: a default prefix is used for the initial startup)
  # <fullname> will evaluate to Cooldowns v<version>
  prefix: '[<fullname>] '
  default_locale: 'en_US'
  available_locales: [en_US]
  # colors: true will enable logging in color (this will only work on non-windows platforms)
  colors: true
  # block_limiter: true will enable a block placement cooldown
  block_limiter: false

groups:
  # Due to the complexity of micro-managing cooldowns and warmups, I'm offering a temporary
  # solution, wherein only commands managed by my plugin are warmed or cooled, and all warmups
  # and cooldowns thereof are global
  default:
    # prefix applies to messages sent by this plugin to the player, such as status messages
    # it does not change chat settings, and should not interfere with any other plugins
    prefix: '[default] '
    type: 'global'
    commands:
      warmup:
        # all values specified are in seconds
        # I'm also providing a few convenience keys, such as _all_
        # _all_ matches all commands, and applies the warmup/cooldown specified
        # _self_ matches the command sender's name, which could be used for limiting /give (as an example)
        _all_: 5
      cooldown:
        _all_: 5
    blocks:
      _all_: 5
  users:
    prefix: '[user] '
    type: 'global'
    commands:
      warmup:
        home: 2
        warp:
          # you may specify the first argument of the command, and it will apply cooldowns
          # to only arguments that have been set in this config
          home: 2
          _all_: 2
      cooldown:
        home: 60
        warp:
          home: 60
          _all_: 120
      # blocks can contain any material you see fit to limit, but will only apply if block_limiter is true
    blocks:
      obsidian: 2
  admins:
    prefix: '[admin] '
    type: 'local'
    commands:
      warmup:
        kill: 2
        tp:
          _self_: 2
          _all_: 2
        time: 2
      cooldown:
        kill: 5
        tp:
          _self_: 60
          _all_: 120
        time: 5
    blocks: