name: Cooldowns
main: net.krinsoft.cooldowns.Cooldowns
version: ${project.version}
author: krinsdeath

commands:
    cooldowns:
      description: Allows setting of various options for this plugin
      aliases: [cooldown, cd]
      usage: |
        /<command> - Shows the user's cooldowns
        /<command> help - displays this menu
        /<command> locale [option] - sets the user's locale to the specified argument
        /<command> setup - Shows the user's settings